ArroyoDev-LLC/components

.github/workflows/build.yml
.projenrc.ts
nx.json
packages/vue/ui/button/.gitignore
packages/vue/ui/button/.npmignore
packages/vue/ui/button/.projen/tasks.json
packages/vue/ui/button/package.json
packages/vue/ui/text/.gitignore
packages/vue/ui/text/.projen/deps.json
packages/vue/ui/text/.projen/tasks.json
packages/vue/ui/text/package.json
pnpm-lock.yaml
projenrc/vue.ts

- feat(projen): set nx config for build pipeline
- fix(vue): use compile for unbuild step
- chore(projen): update projen managed files
Fixes #

fix(ci): NX build pipeline, compile fix

---

.github/workflows/pull-request-lint.yml
.projenrc.ts
.release-please-manifest.json
packages/projen/component/release-please/src/release-please.ts
projenrc/project.ts

- ci(projen): define allowed semantic pr titles.
- feat(projen.component.release-please): load and expose manifest versions.
- feat(projen): set project versions from release-please manifest.
- chore(projen): update managed files
Fixes #

fix(projen.components.release-please): load and set package versions from manifest.

---

pnpm-lock.yaml

chore(deps): dedupe dependencies

---

.github/workflows/release.yml
.projenrc.ts
packages/projen/component/release-please/src/release-please.ts
projenrc/option-builders.ts
projenrc/project.ts

- fix(projen.components.release-please): publish only packaged packages.
- chore(projen): update managed files.
Fixes #

fix(projen.components.release-please): publish only packages with dists

---

.github/images/logo.svg
README.md

This PR updates `README.md` for this project.
- chore(assets): add logo.svg under .github/images/
- docs(README): update + improve README.md
- docs(README): fix broken logo link, add link to .tool-versions in README.md

feat: Improve README.md

---

.github/workflows/release.yml
packages/projen/component/linting/.projen/tasks.json
packages/projen/component/pnpm-workspace/.projen/tasks.json
packages/projen/component/release-please/.projen/tasks.json
packages/projen/component/release-please/src/release-please.ts
packages/projen/component/tool-versions/.projen/tasks.json
packages/projen/component/typescript-source-file/.projen/tasks.json
packages/projen/component/unbuild/.projen/tasks.json
packages/projen/component/vite/.projen/tasks.json
packages/projen/component/vitest/.projen/tasks.json
packages/projen/component/vue/.projen/tasks.json
packages/projen/project/nx-monorepo/.projen/tasks.json
packages/projen/project/typescript/.projen/tasks.json
packages/projen/project/typescript/src/typescript.ts
packages/projen/project/vue-component/.projen/tasks.json
packages/utils/projen/.projen/tasks.json
packages/vue/ui/button/.projen/tasks.json
packages/vue/ui/text/.projen/tasks.json
projenrc/monorepo.ts

- fix(projen.project.typescript): reset packaging test in typescript projects.
- fix(projen): update all packaging tasks.
- fix(projen.component.release-please): publish packages from root
Fixes #

fix: project packaging

---

.github/workflows/build.yml
.github/workflows/release.yml
packages/projen/component/release-please/src/release-please.ts
packages/projen/project/nx-monorepo/src/nx-monorepo.ts

- fix(projen.component.release-please): set global env npm token in release flow
- fix(projen.project.nx-monorepo): set npm auth token env global in build workflow
Fixes #

fix(release): set NPM_TOKEN workflow level envs

---

.projen/tasks.json
packages/projen/project/nx-monorepo/src/nx-monorepo-project-options.ts
packages/projen/project/nx-monorepo/src/nx-monorepo.ts
packages/projen/project/typescript/src/typescript-project-options.ts
packages/projen/project/typescript/src/typescript.ts
projenrc/monorepo.ts
projenrc/option-builders.ts

- refactor(projen.project.nx-monorepo): cleanup default options, remove nx token, default task other
- feat(projenrc): apply nx cloud read-only token in `ComponentsMonorepo`
Fixes #

refactor(projen.project.nx-monorepo): remove nx cloud token, cleanup

---

.projenrc.ts
package.json
packages/projen/project/nx-monorepo/src/nx-monorepo.ts

feat(projen.project.nx-monorepo): move organization common defaults to nx-monorepo project.

---

.projenrc.ts
packages/projen/component/vite/.projen/deps.json
packages/projen/component/vite/.projen/tasks.json
packages/projen/component/vite/package.json
packages/projen/component/vite/src/vite.ts
packages/projen/component/vite/tsconfig.json
packages/projen/component/vue/src/vue.ts
packages/vue/ui/button/.eslintrc.json
packages/vue/ui/button/tsconfig.json
packages/vue/ui/text/.eslintrc.json
packages/vue/ui/text/tsconfig.json
pnpm-lock.yaml
release-please-config.json

- feat(projen.component.vue): add unplugin-vue-macros globals to tsconfig types.
- feat(projen.component.vite): add vite client to tsconfig types.
- feat(vue): update managed vue tsconfigs
Fixes #

feat(vue): add vite and related tsconfig types.

---

.eslintrc.json
.projenrc.ts
packages/projen/component/vitest/src/vitest.ts
packages/vue/ui/button/vitest.config.ts
packages/vue/ui/text/vitest.config.ts
vitest.config.ts

- feat(projen.component.vitest): add sensible vitest defaults
- chore(projenrc): update managed files
Fixes #

feat(projen.component.vitest): sensible defaults

---

packages/projen/project/nx-monorepo/src/typedoc-workflow.ts

fix(projen.project.nx-monorepo): tsdoc github pages workflow build fixes

---

.eslintrc.json
packages/projen/component/linting/.eslintrc.json
packages/projen/component/linting/src/linting.ts
packages/projen/component/pnpm-workspace/.eslintrc.json
packages/projen/component/postcss/.eslintrc.json
packages/projen/component/release-please/.eslintrc.json
packages/projen/component/tailwind/.eslintrc.json
packages/projen/component/tool-versions/.eslintrc.json
packages/projen/component/tsconfig-container/.eslintrc.json
packages/projen/component/typescript-source-file/.eslintrc.json
packages/projen/component/unbuild/.eslintrc.json
packages/projen/component/vite/.eslintrc.json
packages/projen/component/vitest/.eslintrc.json
packages/projen/component/vue/.eslintrc.json
packages/projen/component/vue/src/vue.ts
packages/projen/project/nx-monorepo/.eslintrc.json
packages/projen/project/typescript/.eslintrc.json
packages/projen/project/vue-component/.eslintrc.json
packages/utils/fs/.eslintrc.json
packages/utils/projen/.eslintrc.json
packages/vue/ui/button/.eslintrc.json
packages/vue/ui/text/.eslintrc.json

fix(projen.component.linting): Add `{c,m}.{ts,js}` to eslint import resolvers configs

---

.projen/tasks.json
package.json
packages/projen/component/postcss/.projen/tasks.json
packages/projen/component/postcss/package.json
packages/projen/component/postcss/project.json
packages/projen/component/tailwind/.projen/tasks.json
packages/projen/component/tailwind/package.json
packages/projen/component/tailwind/project.json
packages/projen/component/vite/.projen/tasks.json
packages/projen/component/vite/package.json
packages/projen/component/vite/project.json
packages/projen/component/vitest/src/vitest.ts
packages/utils/fs/.projen/tasks.json
packages/utils/fs/package.json
packages/utils/fs/project.json
packages/utils/projen/.projen/tasks.json
packages/utils/projen/package.json
packages/utils/projen/project.json
packages/vue/ui/button/.projen/tasks.json
packages/vue/ui/button/package.json
packages/vue/ui/button/project.json
packages/vue/ui/text/.projen/tasks.json
packages/vue/ui/text/package.json
packages/vue/ui/text/project.json

feat(projen.component.vitest): add `test:watch` command

---

packages/projen/component/typescript-source-file/src/typescript-source-file.ts

fix(projen.component.ts-source): do not update if no marker and no recreate

---

.projen/tasks.json
packages/projen/project/nx-monorepo/src/nx-monorepo.ts

feat(projen.project.nx-monorepo): execute dev post-install scripts all in parallel using pnpm

---

.envrc
packages/projen/component/dir-env/src/dirEnv.ts
packages/projen/component/dir-env/test/dirEnv.spec.ts

- **feat(projen.component.dir-env): add mise config in buildDefaultEnvRc func**
- **feat(projen): generate projen managed files**
Fixes #

feat: direnv use mise

---

packages/projen/project/typescript/src/builders.ts

fix(projen.project.typescript): resolve type-errors when using tsBuilders on derived projects

---

packages/construct/awscdk/github-pipeline/src/workflow.ts

fix(construct.awscdk.github-pipeline): resolve asset files correctly on latest cdk-github-pipelines version

---

packages/construct/awscdk/github-pipeline/src/workflow.ts

fix(construct.awscdk.github-pipeline): do not overwrite account->stage mappings with later stages

---

packages/construct/awscdk/github-pipeline/src/workflow.ts

fix(construct.awscdk.github-pipeline): ensure unique stage name per account
